---
- hosts: 'all'                                                            
  become: yes
  become_user: root
  gather_facts: yes
  connection: ssh
  tasks:
    - name: Copy script to remote host
      copy: 
        src: wipe-disks.sh
        dest: /tmp/wipe-disks.sh
        mode: 0755
    - name: Clearing the nodes from nbd drives
      ansible.builtin.shell: /bin/bash /tmp/wipe-disks.sh
